dataset:
  name: SmartLab
  dataset_path: /home/threedee/datasets/SmartLab/
  train_dir: train
  val_dir: val
  test_dir: test
  use_cache: False
  class_weights: [1, 1, 1, 1, 1, 1] # [26636, 11195, 12833, 3635, 2720, 1034]
  ignored_label_inds:
    - 0
  num_points: 56000
  test_result_folder: test
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  dim_feature: 8
  dim_input: 3
  dim_output:
    - 16
    - 64
    - 128
    - 256
    - 512
  grid_size: 0.04
  ignored_label_inds:
    - 0
  k_n: 16
  num_classes: 6
  num_layers: 5
  num_points: 56000
  sub_sampling_ratio:
    - 4
    - 4
    - 4
    - 4
    - 2
  t_normalize:
    method: linear
    normalize_points: False
    feat_bias: 0
    feat_scale: 1
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  batch_size: 2
  learning_rate: 0.01
  main_log_dir: logs
  max_epoch: 50
  save_ckpt_freq: 10
  scheduler_gamma: 0.95
  test_batch_size: 3
  train_sum_dir: train_log
  val_batch_size: 3
